### ISSUE TITLE
change guessTheNumber file to

### ISSUE THREAD

**Issue by ToonDiscord** [gizmo-dev/djs-games#6]
change from 

`const djsGames = require('djs-games')
const guessTheNumber = new djsGames.guessTheNumber()
 guessTheNumber.startGame(message)`

to 

`const djsGames = require('djs-games')
const GuessTheNumber = new djsGames.GuessTheNumber()
 GuessTheNumber.startGame(message)`

because djsGames.guessTheNumber is not a constructor.

**Comment by gizmo-dev** [comment]
Fixed it! 
Its now
`const djsGames = require('djs-games') const guessTheNumber = new djsGames.GuessTheNumber() guessTheNumber.startGame(message)`

**Comment by gizmo-dev** [comment]
Fixed it! 
Its now
`const djsGames = require('djs-games') const guessTheNumber = new djsGames.GuessTheNumber() guessTheNumber.startGame(message)`
